---
- name: Playbook with wait timessss
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Initial notification
      debug:
        msg: "Starting the wait period of 10 minutes"

    - name: Completion notification
      debug:
        msg: "Wait period complete"        

    - name: Wait for 10 minutes
      wait_for:
        timeout: 600  # 600 seconds = 10 minutes
      delegate_to: localhost

    - name: Completion notification
      debug:
        msg: "Wait period complete"
