name: Deploy to EC2 via CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Zip Artifact
        run: zip -r nginx-app.zip *

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2

      - name: Upload to S3
        run: aws s3 cp nginx-app.zip s3://softdocs-deployment-testing-471774948982/nginx-app.zip

      - name: Create Deployment
        run: |
          aws deploy create-deployment \
            --application-name nginx-demo-app \
            --deployment-group-name dev \
            --s3-location bucket=softdocs-deployment-testing-471774948982,key=nginx-app.zip,bundleType=zip
